Update Virtualisation.md
CodheadClub/AwesomeResources pull request #154
Opened 2024-08-28 14:09 UTC by einsteinagogo

Added Youtube link for Part 7

2024-08-30 15:31 UTC, closebracket requested changes
Please see the comments. Bloody big PR sir - TY!

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +7. [Part 7: HOW TO: Create your first Windows Virtual Machine on a VMware vSphere Hypervisor 7.0 (ESXi 7.0) Host Server.](https://www.experts-exchange.com/videos/79052/HOW-TO-Create-your-first-Window
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +9. [Part 9: HOW TO: Create your first Linux Virtual Machine Ubuntu 20.04 LTS Server on a VMware vSphere Hypervisor 7.0 (ESXi 7.0) Host Server.](https://www.experts-exchange.com/videos/79073/HOW-TO-Cr
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +10. [Part 10: HOW TO: Create your second Virtual Machine Ubuntu 20.04 LTS Desktop on a VMware vSphere Hypervisor 7.0 (ESXi 7.0) Host Server.](https://www.experts-exchange.com/videos/79074/HOW-TO-Crea
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +11. [Part 11: HOW TO: Install VMware Tools for Linux on a VMware Linux virtual machine on a VMware vSphere Hypervisor 7.0 (ESXi 7.0).](https://www.experts-exchange.com/videos/79092/HOW-TO-Install-VMw
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +12. [Part 12: HOW TO: Install open-vm-tools for Linux on a VMware Linux virtual machine on a VMware vSphere Hypervisor 7.0 (ESXi 7.0).](https://www.experts-exchange.com/videos/79093/HOW-TO-Install-op
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +9. [Part 9: HOW TO: Create your first Linux Virtual Machine Ubuntu 20.04 LTS Server on a VMware vSphere Hypervisor 7.0 (ESXi 7.0) Host Server.](https://www.experts-exchange.com/videos/79073/HOW-TO-Cr
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +10. [Part 10: HOW TO: Create your second Virtual Machine Ubuntu 20.04 LTS Desktop on a VMware vSphere Hypervisor 7.0 (ESXi 7.0) Host Server.](https://www.experts-exchange.com/videos/79074/HOW-TO-Crea
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +11. [Part 11: HOW TO: Install VMware Tools for Linux on a VMware Linux virtual machine on a VMware vSphere Hypervisor 7.0 (ESXi 7.0).](https://www.experts-exchange.com/videos/79092/HOW-TO-Install-VMw
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +12. [Part 12: HOW TO: Install open-vm-tools for Linux on a VMware Linux virtual machine on a VMware vSphere Hypervisor 7.0 (ESXi 7.0).](https://www.experts-exchange.com/videos/79093/HOW-TO-Install-op
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +19. [Part 19: HOW TO: Update VMware ESXi 7.0U1 to ESXi 7.0U2a using VMware vSphere Lifecycle Manager (vLCM).](https://www.experts-exchange.com/videos/79035/HOW-TO-Update-VMware-ESXi-7-0U1-to-ESXi-7-0
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +17. [Part 17: HOW TO: Update VMware ESXi 7.0U2 to ESXi 7.0U2a in 5 easy steps.](https://www.experts-exchange.com/videos/79033/HOW-TO-Update-VMware-ESXi-7-0U2-to-ESXi-7-0U2a-in-5-easy-steps.html) - [A
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +16. [Part 16: HOW TO: Update VMware ESXi 7.0U2 to ESXi 7.0U2a direct from VMware.](https://www.experts-exchange.com/videos/79032/HOW-TO-Update-VMware-ESXi-7-0U2-to-ESXi-7-0U2a-direct-from-VMware.html
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +15. [Part 15: HOW TO: Shrink or Reduce a VMware Virtual Machine Disk (VMDK) using VMware vCenter Converter Standalone v6.2.0.1.](https://www.experts-exchange.com/videos/79096/HOW-TO-Shrink-or-Reduce-
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +14. [Part 14: HOW TO: P2V a Windows XP computer to VMware vSphere Hypervisor 7.0 (ESXi 7.0).](https://www.experts-exchange.com/videos/79095/HOW-TO-P2V-a-Windows-operating-system-computer-to-VMware-vS
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +13. [Part 13: HOW TO: Backup (Export) and Restore (Import) virtual machines to VMware vSphere Hypervisor 7.0 for free.](https://www.experts-exchange.com/videos/79094/HOW-TO-Backup-Export-and-Restore-
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +18. [Part 18: HOW TO: Update VMware ESXi 7U1 (7.0.1) to VMware ESXi 7U2a (7.0.2) using an ISO image.](https://www.experts-exchange.com/videos/79034/HOW-TO-Update-VMware-ESXi-7U1-7-0-1-to-VMware-ESXi-
Ok - Approved.

2024-08-30 15:31 UTC, closebracket commented on README.md
> +![Hancock's VMware Half Hour New Branding](https://andysworld.org.uk/wp-content/uploads/2024/08/AndrewHancock-VMWare-design-VM-and-EE-logos.png)
Please remove the branding image from the contents. I'm happy for you to add images etc to none navigation elements, but if it's in the nav, it's gon' get messy.

2024-08-30 15:31 UTC, closebracket commented on README.md
> +	- [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
If you're changing the nav, please could you reflect that across all files for consistency.

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +## Hancock's VMware Half Hour <a name="hancocksvmwarehalfhour"></a>
Ok. Approved!

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +![Hancock's VMware Half Hour New Branding](https://andysworld.org.uk/wp-content/uploads/2024/08/AndrewHancock-VMWare-design-VM-and-EE-logos.png)
As before - please remove logo from nav

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +9. [VMware vSphere Hypervisor (ESXi)](https://my.vmware.com/en/web/vmware/evalcenter?p=free-esxi7) - Available for free, or full version - Available for free if a Student of The Department of Compute
Broadcom not boradcom. If it's terminated, is it worth just removing the resource? Or does it still run for existing members?

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +2. [VMware Fusion for Apple Mac](https://www.vmware.com/uk/products/fusion.html) - Type 2 Hypervisor for Apple Mac - Available for free if a Student of The Department of Computer Science and Technolo
Broadcom not boradcom. If it's terminated, is it worth just removing the resource? Or does it still run for existing members?

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +3. [VMware Workstation](https://www.vmware.com/uk/products/workstation-pro.html) - Type 2 Hypervisor for Linux and Windows - Available for free if a Student of The Department of Computer Science and
Broadcom not boradcom. If it's terminated, is it worth just removing the resource? Or does it still run for existing members?

2024-08-30 15:31 UTC, closebracket commented on Virtualisation.md
> +4. [VMware Player](https://www.vmware.com/uk/products/workstation-player.html) - Type 2 Hypervisor for Linux and Windows - Available for free if a Student of The Department of Computer Science and Te
Broadcom not boradcom. If it's terminated, is it worth just removing the resource? Or does it still run for existing members?

2024-08-30 15:38 UTC, einsteinagogo commented on Virtualisation.md
> +![Hancock's VMware Half Hour New Branding](https://andysworld.org.uk/wp-content/uploads/2024/08/AndrewHancock-VMWare-design-VM-and-EE-logos.png)
Do you not like the logo?

2024-08-30 15:39 UTC, einsteinagogo commented on Virtualisation.md
> +9. [VMware vSphere Hypervisor (ESXi)](https://my.vmware.com/en/web/vmware/evalcenter?p=free-esxi7) - Available for free, or full version - Available for free if a Student of The Department of Compute
There licenses will still work but going forward it’s terminated but there maybe something new!

2024-08-30 15:39 UTC, einsteinagogo commented on Virtualisation.md
> +2. [VMware Fusion for Apple Mac](https://www.vmware.com/uk/products/fusion.html) - Type 2 Hypervisor for Apple Mac - Available for free if a Student of The Department of Computer Science and Technolo
Ditto

2024-08-30 15:40 UTC, einsteinagogo commented on Virtualisation.md
> +3. [VMware Workstation](https://www.vmware.com/uk/products/workstation-pro.html) - Type 2 Hypervisor for Linux and Windows - Available for free if a Student of The Department of Computer Science and
Ditto I’ll amend on next upload and changed

2024-08-30 15:40 UTC, einsteinagogo commented on Virtualisation.md
> +4. [VMware Player](https://www.vmware.com/uk/products/workstation-player.html) - Type 2 Hypervisor for Linux and Windows - Available for free if a Student of The Department of Computer Science and Te
Ditto

2024-09-05 13:19 UTC, closebracket commented on Virtualisation.md
> +![Hancock's VMware Half Hour New Branding](https://andysworld.org.uk/wp-content/uploads/2024/08/AndrewHancock-VMWare-design-VM-and-EE-logos.png)
> Do you not like the logo?

Not when its embedded in the navigation, no. If you want to put it in Virtualisation.md or add to the dedicated VMware file, that's fine but not in the nav please.

2024-09-05 13:19 UTC, closebracket commented on Virtualisation.md
> +9. [VMware vSphere Hypervisor (ESXi)](https://my.vmware.com/en/web/vmware/evalcenter?p=free-esxi7) - Available for free, or full version - Available for free if a Student of The Department of Compute
> There licenses will still work but going forward it’s terminated but there maybe something new!

Ok - perhaps worth leaving in then, as can point to new programme.

2024-09-05 13:20 UTC, closebracket commented on Virtualisation.md
> +2. [VMware Fusion for Apple Mac](https://www.vmware.com/uk/products/fusion.html) - Type 2 Hypervisor for Apple Mac - Available for free if a Student of The Department of Computer Science and Technolo
> Ditto

As above

2024-09-11 16:13 UTC, closebracket commented on Virtualisation.md
> +55. [Part 55: HOW TO: Check if you have compromised your VMware ESXi 7.0 Hosts if you have added them to Microsoft Active Directory](https://www.experts-exchange.com/videos/80543/HOW-TO-Check-if-you-
Ok - Approved

2024-09-11 16:14 UTC, closebracket commented on Virtualisation.md
> +56. [Part 56: HOW TO: Manually remove a failed vSAN disk group from a VMware vSphere vSAN cluster using ESXCLI](https://www.experts-exchange.com/videos/80594/HOW-TO-Manually-remove-a-failed-vSAN-disk
Ok - Approved

2024-09-11 16:14 UTC, closebracket commented on Virtualisation.md
> +57. [Part 57: HOW TO: Update VMware vSphere Hypervisor ESXi 7.0U3o to ESXi 7.0U3q using VMware vSphere Lifecycle Manager (vLCM)] (https://www.experts-exchange.com/videos/80595/HOW-TO-Update-VMware-vS
Ok - Approved

2024-09-11 16:14 UTC, closebracket commented on Virtualisation.md
> +58. [Part 58: HOW TO: Fix Inaccessible objects in VMware vSphere vSAN when all components show as Active](https://www.experts-exchange.com/videos/80596/HOW-TO-Fix-Inaccessible-objects-in-VMware-vSphe
Ok - Approved

2024-09-11 19:52 UTC, closebracket approved these changes
Approved

2024-09-11 19:52 UTC, closebracket commented on Communities.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:52 UTC, closebracket commented on CyberSecurity.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:52 UTC, closebracket commented on DigitalWarfareGeoPolitics.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:52 UTC, closebracket commented on Electronics.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:52 UTC, closebracket commented on Ethics_Law_Professionalism.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:52 UTC, closebracket commented on Programming.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:52 UTC, closebracket commented on README.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:52 UTC, closebracket commented on Sysadmin.md
> +    - [Hancock's VMware Half Hour](Virtualisation.md#hancocksvmwarehalfhour)
Approved

2024-09-11 19:53 UTC, merged