Update Virtualisation.md
CodheadClub/AwesomeResources pull request #70
Opened 2022-06-06 18:15 UTC by einsteinagogo

Typo in Link

2022-06-07 22:13 UTC, closebracket commented
Did you want this reviewed/approved or is there more to come?

2022-06-11 19:33 UTC, einsteinagogo commented
Okay, can you review, now I've fixed all the links.

2022-06-11 20:34 UTC, closebracket requested changes
Hi @einsteinagogo, this is a huge update which is massively appreciated. Just one change that I can see to the paragraphs in Virtualisation.md. Once that's done, you're ready to be approved.

2022-06-11 20:34 UTC, closebracket commented on Ethics_Law_Professionalism.md
> +    - [Andrew Hancock, VMware vExpert PRO](Virtualisation.md#andrewhancock)
Cool

2022-06-11 20:34 UTC, closebracket commented on Programming.md
> +    - [Andrew Hancock, VMware vExpert PRO](Virtualisation.md#andrewhancock)
Cool

2022-06-11 20:34 UTC, closebracket commented on README.md
> +    - [Andrew Hancock, VMware vExpert PRO](Virtualisation.md#andrewhancock)
Cool

2022-06-11 20:34 UTC, closebracket commented on Virtualisation.md
> +    - [Andrew Hancock, VMware vExpert PRO](Virtualisation.md#andrewhancock)
Cool

2022-06-11 20:34 UTC, closebracket commented on Virtualisation.md
> +7. [Microsoft Hyper-V Server](https://www.microsoft.com/en-us/evalcenter/evaluate-hyper-v-server-2019) - Not to be confused with Windows Server. This is a Type 1 Hypervisor, and is just server core H
Link is working. Thanks for correcting.

2022-06-11 20:34 UTC, closebracket commented on Virtualisation.md
> +Andrew is the VMware Specialist in Computer Science & Technology, responsible for the VMware architecture, "watering & feeding" The Computer Science and Technology VMware vSphere infrastructure. (bas
I'm not sure many people will understand the CS&T references given the lack of association with UoH. Could you please rephrase the paragraphs?

2022-06-11 20:34 UTC, closebracket commented on CyberSecurity.md
> +    - [Andrew Hancock, VMware vExpert PRO](Virtualisation.md#andrewhancock)
Cool

2022-06-11 20:34 UTC, closebracket commented on CyberSecurity.md
> +> ### Disclaimer:
Good shout. Probably worth updating the disclaimer as well. I'll get onto that.

2022-06-11 20:34 UTC, closebracket commented on Electronics.md
> +    - [Andrew Hancock, VMware vExpert PR](Virtualisation.md#andrewhancock)
Seems like it went form PRO to PR?

2022-06-11 20:34 UTC, closebracket commented on Electronics.md
> +    - [Andrew Hancock, VMware vExpert PRO](Virtualisation.md#andrewhancock)
And it was fixed. No problem.

2022-06-11 20:34 UTC, closebracket commented on Virtualisation.md
> +1. [How to Backup an ESXi installation on an USB Flash Drive or SD card for security or redundancy.](https://www.experts-exchange.com/A_5409.html)
Groovy! Thanks for fixing!

2022-06-11 20:34 UTC, closebracket commented on Virtualisation.md
>  3. [HOW TO: Improve the transfer rate of a Physical to Virtual (P2V) Virtual to Virtual Conversion (V2V) using VMware vCenter Converter Standalone 5.0](https://www.experts-exchange.com/articles/9131/
Groovy! Thanks for fixing!

2022-06-11 20:34 UTC, closebracket commented on Virtualisation.md
> +131. [Part 23: HOW TO: BOOT VMware vSphere Hypervisor 7.0 (ESXi 7.0 ARM) from an iSCSI LUN for the Raspberry Pi 4](https://www.experts-exchange.com/articles/35132/HOW-TO-BOOT-VMware-vSphere-Hyperviso
Groovy! Thanks for fixing!

2022-06-11 20:34 UTC, closebracket commented on Virtualisation.md
> +1. [Part 1: HOW TO: Install and Configure VMware vSphere Hypervisor 7.0 U2 (ESXi 7.0.2).](https://www.experts-exchange.com/videos/78972/HOW-TO-Install-and-Configure-VMware-vSphere-Hypervisor-7-0-U2-E
Groovy! Thanks for fixing!

2022-06-11 21:16 UTC, einsteinagogo commented
> Hi @einsteinagogo, this is a huge update which is massively appreciated. Just one change that I can see to the paragraphs in Virtualisation.md. Once that's done, you're ready to be approved.

whats the issue with the Paragraphs, I'm not seeing an issue?

2022-06-11 21:17 UTC, einsteinagogo commented
Okay, I had to expand all the comments, to check what you were referring to!

2022-06-11 21:19 UTC, einsteinagogo commented on Virtualisation.md
> +Andrew is the VMware Specialist in Computer Science & Technology, responsible for the VMware architecture, "watering & feeding" The Computer Science and Technology VMware vSphere infrastructure. (bas
ah! I can see this now, had to expand all comment fields! standby!

2022-06-11 21:44 UTC, einsteinagogo reviewed
okay, I think we are now done.

2022-06-11 21:56 UTC, closebracket commented
> okay, I think we are now done.

Agreed. Good inclusion of EE and fair link to your Ltd given your contributions. Thanks for updating. Will merge.

2022-06-11 21:57 UTC, closebracket approved these changes
Changes made as requested. Approving for merge.

2022-06-11 22:03 UTC, merged